<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UniversalStrategyCore.Base\UniversalStrategyCore.Base.csproj" />
    <ProjectReference Include="..\..\src\UniversalStrategyCore.EconomicSystem\UniversalStrategyCore.EconomicSystem.csproj" />
    <ProjectReference Include="..\..\src\UniversalStrategyCore.Shared\UniversalStrategyCore.Shared.csproj" />
    <ProjectReference Include="..\..\src\UniversalStrategyCore.StrategicConstructionSystem\UniversalStrategyCore.StrategicConstructionSystem.csproj" />
  </ItemGroup>

</Project>